### ISSUE TITLE
Debug on !leavehouse

### ISSUE THREAD

**Issue by HeavenIsLost** [otland/forgottenserver#1403] opened 2015-06-04 20:40 UTC
After i use "!leavehouse" while the servers is removing items from sqm to inbox the client crashs with this log:

http://prntscr.com/7d6kx3

http://prntscr.com/7d6l4o

Edit: if few items no debug, to debug my client need to do this:

http://prntscr.com/7d6pza

Every sqm has 100 crown armors.

if in every sqm there is 10 crown armors then there is no debug. Maybe its related with the count of items in every sqm.

Edit 2: 

If i use internalRemoveItem istead of internalMoveItem(moving from sqm to inbox), still debugs some times.

**Comment by ranisalt** [comment] 2015-06-04 21:46
This was marked as unconfirmed but it is a known and common issue. This happens because of massive amounts of items being pushed into inbox. You could try returning an error on `Inbox::queryAdd` if you detect it is already over capacity.

**Comment by HeavenIsLost** [comment] 2015-06-04 21:56
I don't believe in your idea @ranisalt because i have already changed internalMoveItem to internalRemoveItem(so, the items from the house are simple removed istead of being move to inbox) and it still crashes.

**Comment by WibbenZ** [comment] 2015-06-04 21:58
Lmao on your thread now haha

Tried reading the errors then linking it to the src?
Ill give you a hint "100".

**Comment by ranisalt** [comment] 2015-06-04 22:04
@WibbenZ do you know the debug assertions show errors related to the CLIENT, not the SERVER, right? That Player.cpp is for the source code of the client :P (hope it isn't about that)

**Comment by HeavenIsLost** [comment] 2015-06-04 22:11
Well tibia client crash log(with asserts and such) most of times hints what we are doing wrong.

**Comment by WibbenZ** [comment] 2015-06-04 22:16
99.9% it tells you what the problem is, it's ofc not in hex But in this case it gives a thing we send, an error message about it etc.
To me this is a no brainer - has it been reported before? Links to prev reports? - since you said it's common and kown.

**Comment by djarek** [comment] 2015-06-04 23:03
Perhaps there's something wrong with the code that sends updates to clients? Have you tried checking if it crashes all spectators or just the one using !leavehouse?

**Comment by HeavenIsLost** [comment] 2015-06-05 00:33
@djarek i will try to do more tests to understand more about this issue.

To all, this is a normal issue? every server(tfs 1.x) have it?

**Comment by XtrmJosh** [comment] 2015-06-21 09:37
Is there not a limit of the number of items per tile? If you're stacking 100 I'd imagine you're above that limit? I recall the limit being 32 (including the tile itself), but I could be wrong on this. I definitely remember there being some limit though

**Comment by Codinablack** [comment] 2015-06-21 20:33
The limit you are referring to is probably 255, the same limit that has been in ot since the existence of ot...

**Comment by ranisalt** [comment] 2015-06-22 23:54
The stack of tile items goes from 0 to 255: https://github.com/otland/forgottenserver/blob/56575545a60b2a9927de8fbcff62fc4100eaddfc/data/lib/compat/compat.lua#L12-L20

**Comment by XtrmJosh** [comment] 2015-06-23 08:08
Do you ever remember having to fill a chest full of items, then break it, in order to get more than a certain number of items on a tile? I do.

**Comment by luanlucian93** [comment] 2015-06-25 03:26
Look:
http://i.imgur.com/MqKWFn2.png

I use command: 
select `player_id`, count(`player_id`) from `player_inboxitems` group by `player_id` having count(`player_id`) > 500

Look:
http://i.imgur.com/2DHE9ZG.png

Help me?

**Comment by V-SGFX** [comment] 2015-06-25 08:36
Fuck no! Totally not related to TFS. These are simple MYSQL management commands  - use mysql --help or some manual of MYSQL!

**Comment by HeavenIsLost** [comment] 2016-05-11 04:02
@marksamman  i have tested and the bug exists on 1.1 and does not exists 1.2 after your fix.

**Comment by marksamman** [comment] 2016-05-11 11:10
That's odd, since packet splitting has been supported since c4a27b4b2aa11daf648350f57c8aa0d620166120, it just broke when we merged the network refactor in 1.2, but I guess this issue can be closed then.

**Closed by marksamman** 2016-05-11 11:10 UTC
Labels: bug
