### ISSUE TITLE
Containers bug

### ISSUE THREAD

**Issue by Emilianenko** [otland/forgottenserver#2945] opened 2020-04-18 16:03 UTC
This bug only happens with normal characters ,gamemasters works fine .The bug happens when you have a container full of items, and inside this container a slot with some stackable item, for example a meat ,if i try to move a meat from the ground to the slot with the meat in my backpack i receive "you cannot put more objects in this container" even if i have capacity, and the slot is not full.
This bug seem to be related to this Container::queryMaxCount() failing in special cases. · Issue #1561 · otland/forgottenserver (https://github.com/otland/forgottenserver/issues/1561)
If the player has a large capacity left he can get the item, but if the capacity is low, even having enough to get the item he cannot .
https://vimeo.com/408981185

**Comment by DSpeichert** [comment] 2020-04-18 21:03
@EPuncker Can you help triage this?

**Comment by EPuncker** [comment] 2020-04-19 06:16
> @EPuncker Can you help triage this?

yes I confirm this issue:
![2020-04-19 03_13_](https://user-images.githubusercontent.com/4684880/79680958-ccb60500-81eb-11ea-89fe-8bd8b2a59fd2.png)

I can't move any meat from ground/other container/depot, to any stack of the bag...
but this issue should be closed as it is a duplicate of #1561 and the 1561 should be marked as confirmed

**Comment by DSpeichert** [comment] 2020-04-19 17:51
Closing as duplicate of #1561 
Thanks for the report @Emilianenko

**Closed by DSpeichert** 2020-04-19 17:51 UTC
Labels: duplicate
