### ISSUE TITLE
Experience shared

### ISSUE THREAD

**Issue by M4GO** [otland/forgottenserver#2315] opened 2017-08-28 00:40 UTC
Please Analysis again: https://github.com/otland/forgottenserver/issues/2303
@ranisalt is correct after time shared exp disable.
But if player use healing spell this not disable

**Comment by thexamx** [comment] 2017-08-28 01:12
Healing is not dealing damage, so how it is holding the shared active?
AFAIK shared is only active when every member is dealing damage to monsters.

Correct me if I'm wrong.

**Comment by M4GO** [comment] 2017-08-28 02:32
you make a test ?
make a test and "Correct me if I'm wrong".

**Comment by thexamx** [comment] 2017-08-28 11:51
Confirmed it happens.
But you still cant go further than 30 sqm away from leader.

https://github.com/otland/forgottenserver/blob/master/src/party.cpp#L422-L457

**Comment by ranisalt** [comment] 2017-08-28 13:11
Wrong, if that was true then healers wouldn't share exp. You keep on sharing if you heal party members, including yourself, but if you don't heal anyone who is actively fighting then your idle time keeps ticking.

it would be an issue only if a player not actively fighting keeps sharing after healing himself only for over 45s.

**Comment by M4GO** [comment] 2017-08-28 13:31
@ranisalt this don't disabled for xtime if player healing himself he can up hours an hours

**Comment by soul4soul** [comment] 2017-11-02 12:09
Possible duplicate of #1540

**Comment by HeavenIsLost** [comment] 2017-11-03 22:58
You may fix it replacing this line: https://github.com/otland/forgottenserver/blob/master/src/player.cpp#L3464 with this line of code "if (isPartner(tmpPlayer) && (tmpPlayer != this)) {"

**Comment by malucooo** [comment] 2018-04-12 18:37
@HeavenIsLost i have replaced this line, but isn't work =/

**Comment by soul4soul** [comment] 2018-06-12 19:46
@DSpeichert This issue was fixed with #2471

**Comment by DSpeichert** [comment] 2018-06-12 22:19
Fixed in #2472

**Closed by DSpeichert** 2018-06-12 22:19 UTC
Labels: unconfirmed
