### ISSUE TITLE
Experience Share giving less experience with different stages

### ISSUE THREAD

**Issue by TwistedScorpio** [otland/forgottenserver#1236] opened 2015-03-16 21:39 UTC
Basically I have two players:

Level 305 and Level 260

Experience rate for level 305 is 5x, experience rate for 260 is 7x.

NOTE: I modified the Amazon experience to be 2100.
So if Level 305 kills the Amazon and is not in a party he will get 10500 experience *  1.5 (stamina bonus) = 15750

But when shared experience with only Level 260 in the party, he will get as low as 11032.

This happened in the latest commit of TFS 1.1-development.

Pictures:
![image](https://cloud.githubusercontent.com/assets/6238582/6677084/11292400-cbea-11e4-894a-2f7a68518f27.png)

![image](https://cloud.githubusercontent.com/assets/6238582/6677096/27e8f710-cbea-11e4-9d75-d6f9ca8ed3c4.png)

**Comment by Kamenuvol** [comment] 2015-03-16 22:42
Exp Stage and Rate should be the last thing to multiply:
total: stageRate * happyHour * ceil(exp * (1/members + partyBonus))
In this case:
total: 5 * 1,5 * 2100 * (0,5 + 0,2)
level 305: 11025
level 260: 15435

It is not the same but is near and correct according to the sources.

**Comment by TwistedScorpio** [comment] 2015-03-16 22:48
So the fact that after experience share the lvl 305 gets less experience with shared exp is normal ?

**Comment by Kamenuvol** [comment] 2015-03-16 22:53
Yes, because of the expStage. Both characters should gain the same without it, whenever shareExp is activated.

However, we need to see why the xp numbers are not exactly correct.

**Comment by Kamenuvol** [comment] 2015-03-16 23:20
I am doing reverse mathematics =P and I see that:
15445,5 / 7 = 11032,5 /5
There is something multiplying 1,00068... to the result. I wonder what.

**Comment by Kamenuvol** [comment] 2015-03-16 23:38
Yes, the problem is using ceil to round 1470.xxxx to 1471. And it messes up everything, may we need to check Tibia Global to see what happens.
I have tested with this code:
http://www.heypasteit.com/clip/1V5E
And it returns the same as your xp.

**Comment by marksamman** [comment] 2015-10-07 15:08
This may have been fixed by #1579, please open a new issue if the issue persists.

**Closed by marksamman** 2015-10-07 15:08 UTC
Labels: unconfirmed
