### ISSUE TITLE
Visual error

### ISSUE THREAD

**Issue by Weeboo** [otland/forgottenserver#1755] opened 2016-04-06 14:03 UTC
Severity	Code	Description	Project	File	Line	Suppression State
Error	C2338	You've instantiated std::atomic<T> with sizeof(T) equal to 2/4/8 and alignof(T) < sizeof(T). Before VS 2015 Update 2, this would have misbehaved at runtime. VS 2015 Update 2 was fixed to handle this correctly, but the fix inherently changes layout and breaks binary compatibility. Please define _ENABLE_ATOMIC_ALIGNMENT_FIX to acknowledge that you understand this, and that everything you're linking has been compiled with VS 2015 Update 2 (or later). (compiling source file ..\src\outputmessage.cpp)	theforgottenserver	C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\atomic	661

**Comment by ranisalt** [comment] 2016-04-06 14:09
Duplicate of #1754

**Closed** 2016-04-06 14:17 UTC
Labels: duplicate
