### ISSUE TITLE
onHealthChange: Doesn't execute for healing

### ISSUE THREAD

**Issue by Codinablack** [otland/forgottenserver#1226] opened 2015-03-11 22:20 UTC
Ok so I am not for sure if this is the intended use of the event or not, but I know whenever a player heals thru regen, or through using a potion or something like that onHealthChange is not called or executed at all. I was merely trying to test if my regen alteration was working so I was trying to print the damage, I assumed it would give me atleast some number and I could consider the absolute value of that number the increase of health be it negative or positive, but I never got a number. So I made this simple script to test if it was even being called...

function onHealthChange(creature, attacker, primaryDamage, primaryType, secondaryDamage, secondaryType, origin)
    print("It's loading")
    return primaryDamage, primaryType, secondaryDamage, secondaryType
end

Nothing gets printed....

**Comment by marksamman** [comment] 2015-03-12 09:28
IMO onHealthChange should be triggered for every kind of health change, even regeneration; this seems like a duplicate of #1211 though as @dalkon has mentioned that onHealthChange also could be extended in a comment in that issue.

**Closed by marksamman** 2015-03-12 09:28 UTC
Labels: duplicate

**Comment by Codinablack** [comment] 2015-03-28 08:09
Sorry forgot about that one, origin needs to be something other than ORIGIN_NONE, but that could possibly be changed. Thank you
