### ISSUE TITLE
Urgent bug in PULL REQUEST (1340)

### ISSUE THREAD

**Issue by rowaraujo** [otland/forgottenserver#1350] opened 2015-05-11 16:18 UTC
Pull Request: #1340 
It is possible to pass through the walls. Just activate the "dash" function in OTClient.
Tibia Bots to the original client is even worse, because the "dash" is higher.
![bug](https://cloud.githubusercontent.com/assets/9668277/7569599/2d64d4bc-f7e0-11e4-8f55-354c4f02e352.png)
How to rely on updates?

**Comment by marksamman** [comment] 2015-05-11 18:54
You don't rely on the bleeding edge updates, there may be experimental untested changes. If you need something reliable, use one of the releases tagged here: https://github.com/otland/forgottenserver/releases.

**Comment by djarek** [comment] 2015-05-11 21:43
I can confirm this bug. It can be quick fixed by changing this (tile.cpp:1453)
```
 			if (ground == nullptr) {
 				ground = item;
				setTileFlags(item);
 			}
```
 to this:

```
 			if (ground == nullptr) {
 				ground = item;
 			}
 			setTileFlags(item);

```
However, a proper solution should be found. It seems it is caused by some external code setting the ground item on a Tile which already has one set during a map load. It wouldn't surprise me if there's a potential leak of ground items somewhere in that calling code.

**Comment by marksamman** [comment] 2015-05-12 09:22
I did notice that setTileFlags would no longer be called for the item if it wasn't being assigned to the tile, but assumed that wouldn't matter because we shouldn't assign flags to a tile of an item which isn't present on the tile. I'm more interested in figuring out why this actually happens than just applying a quick-fix, it's not really urgent to fix it at this stage anyway.

**Comment by djarek** [comment] 2015-05-12 12:47
Actually, that did not fix this bug. The problem wasn't with the flag setting or the ground item being set more than once. The issue is in Tile::queryAdd(), which doesn't check if a tile is blocking if the item vector hasn't been created.

**Comment by rowaraujo** [comment] 2015-05-12 15:39
Does that make sense?
![print](https://cloud.githubusercontent.com/assets/9668277/7591380/f22dc768-f8a3-11e4-9f27-35aba8823ad2.png)

**Comment by djarek** [comment] 2015-05-12 22:08
That isn't relevant. The issue was caused by one piece of code relying on incorrect behavior in an another piece of code. Once the bug was fixed in the latter, the latent bug surfaced in the former.

**Closed** 2015-05-13 18:56 UTC
Labels: bug
