### ISSUE TITLE
[Crash] Creature::executeConditions

### ISSUE THREAD

**Issue by ninjalulz** [otland/forgottenserver#2024] opened 2016-12-15 12:42 UTC
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Use an [onPrepareDeath script](http://pastebin.com/cuUcsBDP) which removes one condition or more with the help of Creature.removeCondition. However you can bypass the crash if you replace L9 with condition:setTicks(0), but it doesn't remove the condition immediately.
2. Kill your target with a dot (damage-over-time) spell or rune.

### Expected behaviour
Removes the condition safely.

### Actual behaviour
Server crashes. It might not always crash for you, but it did for me at least.

### Stacktrace
http://pastebin.com/cQKYN9kW

### Environment
macOS 10.12 (Sierra) / Ubuntu 15.10 (Wily Werewolf).

**Comment by wgrriffel** [comment] 2016-12-17 21:44
i can confirm this.

**Comment by wgrriffel** [comment] 2016-12-18 00:38
i think this block https://github.com/otland/forgottenserver/blob/master/src/creature.cpp#L1302-L1311 `it` is a dangling pointer, since it was deleted on `Creature::removeCondition`, not sure tho.

**Comment by vankk** [comment] 2016-12-18 00:52
The fix for this issue is:

`void Creature::executeConditions(uint32_t interval)
{
    auto it = conditions.begin(), end = conditions.end();
     while (it != end) {
        Condition* condition = *it;
        if(!condition) {
            it = conditions.erase(it);
            continue;
        } else if (!condition->executeCondition(this, interval)) {
            ConditionType_t type = condition->getType();

            it = conditions.erase(it);

            condition->endCondition(this);
            delete condition;

            onEndCondition(type);
        } else {
            ++it;
        }
    }
}`

**Comment by gugahoa** [comment] 2017-01-06 06:12
I can't reproduce it no matter how many times I try, could you share the crash report if possible?

**Comment by ninjalulz** [comment] 2017-01-06 13:08
@gugahoa You can view it by clicking on the pastebin link above.

**Comment by gugahoa** [comment] 2017-01-06 13:25
Ops, I expected a wall of text somewhere in the issue hahaha

**Comment by gugahoa** [comment] 2017-01-08 02:16
Could reliable reproduce this: Step on fire field and let the tick damage kill you

**Comment by Eternal-Scripts** [comment] 2017-06-21 18:21
![screenshot_2](https://user-images.githubusercontent.com/20959344/27400040-37195af8-5695-11e7-8adc-e3a165b32ad5.png)
![screenshot_3](https://user-images.githubusercontent.com/20959344/27400041-371ad716-5695-11e7-9932-07dd68873444.png)
Crash

**Comment by joseluis2g** [comment] 2017-06-21 19:26
@Eternal-Scripts How did you reproduce it?

**Comment by Eternal-Scripts** [comment] 2017-06-21 19:42
@joseluis2g I don't know my friend, my server is online and when i open gdb i see that.

**Comment by joseluis2g** [comment] 2017-06-21 22:50
@Eternal-Scripts 
If you find out the solution I would be very happy if you share it with me, imma do the same.

**Comment by jo3bingham** [comment] 2017-06-21 23:03
@Eternal-Scripts, could you supply a stacktrace to compare against @ninjalulz's? Those screenshots don't really help.

**Comment by Eternal-Scripts** [comment] 2017-06-21 23:19
@jo3bingham Yes, but i lost the first printscreen (two in total).
Second:
![screenshot_4](https://user-images.githubusercontent.com/20959344/27410588-eb17cda4-56be-11e7-872c-0a6a27ce9b61.png)

**Comment by joseluis2g** [comment] 2017-06-21 23:20
@Eternal-Scripts 
are you using the version with mkalo changes?

**Comment by Eternal-Scripts** [comment] 2017-06-21 23:21
@joseluis2g Yes, i will try crash again in my tfs and i will answer here.

**Comment by joseluis2g** [comment] 2017-06-21 23:25
I had lot of logs with the same problem, when im back at home gonna edit this post.

**Comment by darkjav** [comment] 2017-06-27 00:17
@joseluis2g @Eternal-Scripts 
What mkalo changes  do you mean?

**Comment by TaigaTenori** [comment] 2018-02-11 06:13
Maybe an old issue, but still open. Tried to reproduce on win 10 with ninja's script and using this .exe https://ci.appveyor.com/project/kornholi/forgottenserver/build/job/8oncjox5thiv0uct/artifacts.

Script was working, I couldn't die. I had a fire condition on me repeatedly from walking onto fire fields, which was being properly removed on supposed death. No crashes

**Comment by kito2** [comment] 2018-02-17 12:20
Still happening:

https://pastebin.com/tiKAN2xp

**Comment by DSpeichert** [comment] 2018-07-08 05:45
I could reproduce as of  5438d50

**Comment by jo3bingham** [comment] 2019-03-11 21:46
I got around to checking this bug report out today. Luckily, it's reproducible 100% of the time, which helped me track down the exact cause. I'll outline it below:

To begin, conditions are executed on a regular interval when checking creatures:
https://github.com/otland/forgottenserver/blob/ba0be848318923edd28f8f8bbfd39ed0c405c34f/src/game.cpp#L3599

The function called iterates through every condition the creature has and tries to execute them:
https://github.com/otland/forgottenserver/blob/ba0be848318923edd28f8f8bbfd39ed0c405c34f/src/creature.cpp#L1286

Because this is a `ConditionDamage` type condition, and it does damage over a period of time, it calls `ConditionDamage::doDamage`:
https://github.com/otland/forgottenserver/blob/ba0be848318923edd28f8f8bbfd39ed0c405c34f/src/condition.cpp#L1101
Which calls into `Game::combatChangeHealth`:
https://github.com/otland/forgottenserver/blob/ba0be848318923edd28f8f8bbfd39ed0c405c34f/src/condition.cpp#L1176

This is where `onPrepareDeath` events are triggered:
https://github.com/otland/forgottenserver/blob/ba0be848318923edd28f8f8bbfd39ed0c405c34f/src/game.cpp#L4177

You can see where this is going... Because your `onPrepareDeath` event script calls `player:removeCondition`, which calls `Creature::removeCondition`, the same iterator that `Creature::executeConditions` is currently using is then removed from the condition list:
https://github.com/otland/forgottenserver/blob/ba0be848318923edd28f8f8bbfd39ed0c405c34f/src/creature.cpp#L1254

I'm currently contemplating a proper fix, but others feel free to chime in.

**Comment by Znote** [comment] 2019-03-11 23:26
Perhaps find a way to add remove condition requests in a queue? A soft remove until executeConditions is done triggering active conditions?
![image](https://user-images.githubusercontent.com/1552144/54164578-69409c00-445d-11e9-8f8d-5024d6553169.png)

**Comment by jo3bingham** [comment] 2019-03-12 11:39
> Perhaps Creature::executeConditions should be the only thing allowed to remove conditions, and the other condition functions only flag itself to deletion. Which then is checked and deleted the next time executeConditions triggers?

This is the conclusion I came to. Considering `Creature::executeConditions` is invoked regularly, cleaning up there makes sense. Will make a PR.

**Closed** 2019-03-14 11:57 UTC
Labels: bug
