### ISSUE TITLE
MonsterType(name):getLoot() Crash

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1732] opened 2016-03-02 10:14 UTC
Hello,

well when you unlock a monster, then you are able to view that monster information when you select the monster on the modalwindow. But i noticed sometimes it crash and i tracked it down to monsterLoot:
http://3.1m.yt/WSO4dzt.png

**Comment by PrinterLUA** [comment] 2016-03-03 20:00
@marksamman 
I have gdb crashlog, if it easier to debug with it. Since i have no idea how to debug stuff:
http://pastebin.com/53tCxmAQ

**Comment by marksamman** [comment] 2016-03-03 20:09
If you can post the XML file for the monster that this is happening with, perhaps we'll be able to reproduce it and get a better idea of why it's happening. If you still have that core file, you can run this in gdb to get the monster name:
```
frame 4
p monsterType.name
```

**Comment by PrinterLUA** [comment] 2016-03-03 20:23
I get this error:
`
(gdb) frame 4
#4  0x00000000009a20aa in LuaScriptInterface::luaMonsterTypeGetLoot(lua_State*)
    ()
(gdb) p monsterType.name
No symbol "monsterType" in current context.
`

It happens to all the monster, and the monster are just from theforgottenserver. I'm the one causing the crash. So i tested with Cave Rat.

**Comment by marksamman** [comment] 2016-03-03 20:52
Post the script for your modal window event.

**Comment by PrinterLUA** [comment] 2016-03-03 21:23
Since my original code, is over 1k lines. I breaked it down and still cause crash. But need follow these steps to reproduce it:
First create lua in actions folder and make sure it has a -Use With- (aim)
So first target anywhere, expect yourself! After it printed out in the console the loot, then target yourself and click view button. Boom crash. Atleast for me.
http://pastebin.com/XJUFbB8K
http://pastebin.com/5tk3N3gv

**Comment by PrinterLUA** [comment] 2016-03-04 16:53
@marksamman were you able to reproduce?

**Comment by Eternal-Scripts** [comment] 2017-01-10 18:25
I can confirm this.

**Comment by PrinterLUA** [comment] 2017-01-15 12:47
Maybe it should be changed to bug @ranisalt

**Comment by ninjalulz** [comment] 2017-01-16 12:20
I couldn't reproduce this on macOS & Ubuntu.

**Comment by PrinterLUA** [comment] 2017-01-16 12:37
Hm, maybe Windows only?

**Comment by vankk** [comment] 2017-12-22 03:51
I couldn't reproduce this on Windows 10 and Ubuntu 14.04.

**Comment by gunzino** [comment] 2018-04-30 08:46
I experience the same problem with function monsterType:getLoot()

**Comment by M4GO** [comment] 2020-09-30 22:51
I have this problem. to reproduce add systems
https://otland.net/threads/reward-chest-boss-reward-tfs-1-2.238554/
https://github.com/otland/forgottenserver/commit/38eb0cde9eb579765a7e9588eb3d214312d55a19
two players kill the boss

**Comment by EPuncker** [comment] 2020-09-30 23:20
> I have this problem. to reproduce add systems
> https://otland.net/threads/reward-chest-boss-reward-tfs-1-2.238554/
> [38eb0cd](https://github.com/otland/forgottenserver/commit/38eb0cde9eb579765a7e9588eb3d214312d55a19)
> two players kill the boss

lol the bug should be able to be reproduced without any code change or it won't be on tfs but on the system you added

**Comment by DSpeichert** [comment] 2020-10-13 04:14
Closing as majority of people can NOT reproduce it and it's likely irrelevant after so much time.

**Closed by DSpeichert** 2020-10-13 04:14 UTC
Labels: bug
