### ISSUE TITLE
Client Crash with TFS 1.2 

### ISSUE THREAD

**Issue by DarkShaooz** [otland/forgottenserver#1782] opened 2016-04-30 15:23 UTC
Greetings!
I have a problem right now, I just downloaded TFS 1.2 distro and compiled it with 
Visual Studio 2015 Update 1...
Im using TFS-SDK 3.2, Boost 1.60 and the recent TFS 1.2 
Everything complies good, but when I run the tfs.exe and try to log in to my admin account in the client, it crashes... 
I tried to change the client version but it crashes aswell. When i enter a wrong account it appears the msg "Invalid Account" but when I enter a correct account it crashes. I didn't do anything wrong I followed the guide step by step...

Any idea what is happening? 
Thanks

**Comment by DarkShaooz** [comment] 2016-04-30 17:39
I downloaded another Bistro from OTland, and I compiled it and works fine, any idea why the TFS from github doesn't work?

**Comment by Marahin** [comment] 2016-05-01 01:21
Go through compilation warnings if you have any. That should be the first step of debugging.

**Comment by wgrriffel** [comment] 2016-05-01 02:53
I just compiled about now latest sources and working fine, though I'm using debian 8, it could be related to #1754, try to downgrade to vs14 or 13, Idk why microsoft has to fuck up everything on every release of VS, this is related to VS and not TFS.

**Comment by DarkShaooz** [comment] 2016-05-02 06:00
I don't have any compilation warnings, I was watching that since the beggining but nothing, it compiles good.
It's something from the VS or the libraries I downloaded to compile it..

**Comment by ranisalt** [comment] 2016-05-02 17:40
Open it using a debugger and see exactly where it crashes.

[MSVC compiler is a pile of shit anyway.](http://stackoverflow.com/questions/31529327/c-is-it-worth-using-gcc-over-msvc-on-windows)

**Comment by wgrriffel** [comment] 2016-05-02 20:57
Did you tried to use vs14 or vs13 instead? because i downloaded the [nightly builds for Windows](http://nightlies.otland.net/) and nothing happens to me, maybe can be your source modifications, if doesn't work anyway try to generate a makefile from cmake and compile with mingw, however im not sure if cmake can generate without errors, probably will.

**Comment by marksamman** [comment] 2016-05-08 20:52
Perhaps you are using an unsupported client. No one has been able to reproduce this, so I'm closing this issue as there's nothing we can do about it without more information on how to reproduce it.

**Closed by marksamman** 2016-05-08 20:52 UTC
Labels: invalid

**Comment by wgrriffel** [comment] 2016-05-09 02:14
@DarkShaooz did you changed the position of character? because if you are at default nil map you will get crash everytime, try to get temple position of your map.
