### ISSUE TITLE
Compile error Visual Studio 2015

### ISSUE THREAD

**Issue by Alscara** [otland/forgottenserver#1514] opened 2015-08-12 01:31 UTC
When compiling in VS2015, I get this error:
1>LINK : fatal error LNK1104: cannot open file 'libboost_system-vc140-mt-1_58.lib'
Due to the solution being too old, it has to be upgraded from vc120 to vc140 and then during the build after it finishes wildcardtree, this error comes up, just before the point where it would normally say "generating code".

**Comment by Codinablack** [comment] 2015-08-12 04:15
I have the same problem. I started off on the support forums on otland and my post on there isn't that old however no one has responded with a way to fix this...

**Comment by EvulMastah** [comment] 2015-08-12 07:59
Don't worry guys, I have travelled the world to seek knowledge about this error. It took 10 years to find the solution, but it is finally here. You need boost libs compiled for visual studio 2015.

**Comment by Codinablack** [comment] 2015-08-12 14:58
Sweet! @EvulMastah thanks for being no help and making fun of us at the same time. I don't know how to "compile" boost libs for msvs2015 and I tried making the change I found here

https://github.com/boostorg/config/pull/60/files

But it didn't work. I have used google and many people have the same problem but they all say different ways to fix it, and i don't know how to compile boost, thought they were libraries that didn't need compiled, how about being a little bit more help plz?

**Comment by EvulMastah** [comment] 2015-08-12 15:12
Well, what does your lack of knowledge has to do with this project? Is this forgotten servers bug? Not really. Open an issue on boosts repository is you have problem with it, not here.

**Comment by Codinablack** [comment] 2015-08-12 15:21
Alright well I didn't understand what the problem was thats why i started the issue on otland.net. No need in being a jerk, I see now that what we have downloaded are binaries, and it's gotta be compiled for this visual studio version, however I have never done that, would you be so kind as to point me to a place that hosts those binaries for this visual studio version?

**Comment by Codinablack** [comment] 2015-08-12 15:29
@Alscara this is a problem with boost not with forgottenserver, so please close this issue, when I get time off tomorrow I will try to compile boost for this particular version of vs and if I succeed I will post on otland for everyone else who needs the binaries.

@EvulMastah we are asking for help not ridicule. Our "lack of knowledge" is what led to this issue being posted here, sorry we are noobs, maybe next time you will be of some actual help to someone seeking it. I am not asking for handouts or someone to do the work for me, I understand what the issue is and I will work on solving it, although I have never compiled boost before I am certain I can do it.

**Comment by Nu77** [comment] 2015-08-12 22:26
@Alscara @Codinablack just use the bin installer and should be fine.

**Comment by Codinablack** [comment] 2015-08-13 04:26
There isn't one for MSVS14.0 which is what we are using...

**Comment by TwistedScorpio** [comment] 2015-08-15 00:44
Well then just install VS2013 to get the v120 Platform Toolset and compile with VS2015.

**Comment by Alscara** [comment] 2015-08-15 06:50
@TwistedScorpio By all means, if you can find VS2013, I'll download it. But I downloaded the standalone 2013 build tools since that's all I could find and it made no difference.

**Comment by ranisalt** [comment] 2015-08-16 03:03
@Codinablack Boost 1.59.0 has released a version for VS14 just after your reply :P

**Closed** 2015-08-16 05:44 UTC
Labels: invalid
