### ISSUE TITLE
Debug when going upstairs (ramp with id 1559)

### ISSUE THREAD

**Issue by gugahoa** [otland/forgottenserver#1338] opened 2015-05-09 06:28 UTC
The debug happens only if your looktype is an outfit. (If I'm in /ghost mode, it does not debug. If I'm using an outfit, it does.)

http://imgur.com/p9uljVq,2e1lhUe,qEtz4zJ
In the first images there's the debug message
On the second I show what happens if I throw a backpack (The position of the backpack is 33151, 32790, 3)
On the third I show the sqm that'll trigger the debug

**Comment by Pwntus** [comment] 2015-05-09 07:23
Just tried it myself and my client will crash on **every** "corner" of the pyramid. However, as you said, if I'm invisible everything works as it should.

**Comment by PrinterLUA** [comment] 2015-05-09 08:21
I suspect it has todo something with this commit:
https://github.com/otland/forgottenserver/commit/6c03744498b9813cca8d052d84c3f15188878ddd

Since some of these directions, cannot be achived in the client visually: DIRECTION_NORTHEAST, DIRECTION_NORTHWEST, DIRECTION_SOUTHEAST and DIRECTION_SOUTHWEST.

**Comment by Pwntus** [comment] 2015-05-09 10:46
I think something like this is happening, the red square is the position the player is placed.

![Illustration](http://i.imgur.com/5gkIkvY.png)

**Comment by gugahoa** [comment] 2015-05-09 14:48
When trying to do it with OTClient, the direction the player will face after going upstairs is always his right side

**Comment by rowaraujo** [comment] 2015-05-09 15:43
I tried to talk that my server had many debugs, but Mark just ignored me just because I had put Cast System.
Other items are also the same problem. The ids are: 1553, 1555, 1557 and this 1559.
To avoid the debugs for now, you can change the ids for the others i found the same look and it does not allow the passage:
1553 -> 1578
1555 -> 1579
1557 -> 1580
1559 -> 1581

**Comment by Pwntus** [comment] 2015-05-10 00:47
Temporary fix: #1345

**Comment by PrinterLUA** [comment] 2015-05-10 06:19
The temporary fix is to disable this line:
https://github.com/otland/forgottenserver/blob/master/src/game.cpp#L870

@marksamman i have tested and i can confirm it.

**Comment by gugahoa** [comment] 2015-05-10 06:35
It seem it happens when trying to turn to a diagonal position. In this case, how does it works on global? Can anyone test?

**Comment by PrinterLUA** [comment] 2015-05-10 07:01
As i metion on my previous comment, there is 4 directions that cannot be displayed visually. Since getDirectionTo is fetching those directions and display it cause client crash.

**Comment by gugahoa** [comment] 2015-05-10 07:58
True, I passed by the comment and didn't read it, sorry.

**Comment by marksamman** [comment] 2015-05-15 10:39
Fixed in c4a707201c7c69c2a150a4892b736f4a45ddfa96.

**Closed by marksamman** 2015-05-15 10:39 UTC
Labels: bug
