### ISSUE TITLE
Paralyze rune not work how intended

### ISSUE THREAD

**Issue by darkjav** [otland/forgottenserver#2290] opened 2017-07-29 19:40 UTC
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Player use paralyze rune in another player with equipment that raises speed, for example prismatic armor, grasshopper legs, boots of haste, time of ring, etc.
2. Targeted player get decreased speed, but not to 40.

### Expected behaviour
Paralyze rune must decrease speed to 40, does not matter if player have equipment that raises the speed or not.

Paralyze rune must work like RL.

### Actual behaviour
Paralyze rune not decrease speed to 40, if the player has equipment that increases the speed, for example boots of haste, time of ring, etc.

Only work if the player not have equipment of speed.

### Environment
TFS 1.3
Ubuntu 14.04

**Comment by thexamx** [comment] 2017-07-30 00:34
Any source or evidence, that your informations are actually correct?

**Comment by WibbenZ** [comment] 2017-12-26 20:28
Seeing as no one has helped to confirm this issue im closing it.
Feel free to inform us if the issue is still present.

**Closed by WibbenZ** 2017-12-26 20:28 UTC
Labels: unconfirmed
