### ISSUE TITLE
throwing items on bookcases

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3405] opened 2021-04-08 07:36 UTC
### Expected behaviour
should not be possible to throw items ontop of bookcases, and it should return "There is not enough room."

i'm not sure tho if we should only check for the id's of those or if other items is involved aswell.

### Actual behaviour
https://imgur.com/a/OmC7zaU

**Comment by EPuncker** [comment] 2021-04-08 23:29
confirmed, but need to check if this is tfs items.otb fault or if it was still possible to do on tibia version 10.98

**Comment by MillhioreBT** [comment] 2021-04-09 01:53
It seems logical that you can above throw something on a bookcase, It doesn't seem like it looks good to the eyes because it's a 2D world, However, at this point it is impossible to check if in version 10.98 this worked like this in tibia rl, I support the idea that it should work as it does in current tibia rl

**Comment by emil92b** [comment] 2021-04-11 09:05
it wasn't possible in earlier versions either

**Comment by nekiro** [comment] 2021-04-15 13:24
This is probably directly related to attributes parsed from dat file to items.otb, so nothing to fix here server side.

**Comment by EPuncker** [comment] 2021-04-24 22:46
I'm closing this in favor of:
- we can't know/confirm how it worked back in the days
- it can be easily achievable with a simple OnMoveItem event
- this is more likely to be a client side thing as stated before

**Closed by EPuncker** 2021-04-24 22:46 UTC
Labels: good first issue
