### ISSUE TITLE
Searchtype name typo?

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1206] opened 2015-02-18 15:41 UTC
Hello, well i wonder is the name correct? TARGETSEARCH_NEAREAST or TARGETSEARCH_NEAREST?

If it should be nearest, then it is not working as intended. It still just picking a target, who is further away.

**Comment by ninjalulz** [comment] 2015-02-18 16:13
TARGETSEARCH_NEARE<b>A</b>ST is the correct one.

**Comment by marksamman** [comment] 2015-02-18 16:59
Please clarify when it is not working as intended; how do you define further away?

**Comment by PrinterLUA** [comment] 2015-02-18 17:14
I did not test your changes, or if they are meant to fix it. But this is what i meant:
http://2.ii.gl/diC65xTOS.gif

**Comment by marksamman** [comment] 2015-02-18 17:25
The old code should have targeted the left-most monster too, so it shouldn't matter. How are you trying to use TARGETSEARCH_NEAREST?

**Comment by PrinterLUA** [comment] 2015-02-18 17:30
Well now with the latest commit, it attack the nearest target. Is it random? Since i did not make any changes yet.

**Comment by marksamman** [comment] 2015-02-18 17:45
I'm not asking you **what** you are trying to do, I'm asking **how**. How are you calling searchTarget? From where?

**Comment by PrinterLUA** [comment] 2015-02-18 17:52
monster.cpp void Monster::onThink(uint32_t interval)

Replaced:
searchTarget(TARGETSEARCH_ATTACKRANGE);
with
searchTarget(TARGETSEARCH_NEAREST);

**Comment by marksamman** [comment] 2015-02-18 18:53
NEAREST will target the nearest creature that the monster can currently reach with any of its abilities, the monster you summoned can't reach any of the targets with its abilities and will just pick the first entry in the target set. Marking this as an enhancement to change that behavior to pick the nearest of all unreachable targets if there isn't any reachable target.

**Comment by PrinterLUA** [comment] 2015-02-18 21:37
Great, i made it through lua. But is it bad idea to doing it through lua?

**Closed** 2015-04-05 08:59 UTC
Labels: enhancement
