### ISSUE TITLE
Suggestion: Move monster drop loot to Lua

### ISSUE THREAD

**Issue by gugahoa** [otland/forgottenserver#1249] opened 2015-03-23 13:51 UTC
I would like to suggest moving monster drop to Lua. It would need some enhancement on the source so that a onDeath event can be easily registered to every monster easily. 

This would make it possible to customize the drop based on certain conditions.

**Comment by marksamman** [comment] 2015-03-23 20:30
Duplicate of onDropLoot suggested in #1049

**Closed by marksamman** 2015-03-23 20:30 UTC
Labels: duplicate
