### ISSUE TITLE
Remove Conditions doesn't work

### ISSUE THREAD

**Issue by ghost** [otland/forgottenserver#2257] opened 2017-05-16 09:37 UTC
Remove conditions doesn't work, it doesn't remove a condition by default or subid... only 2 ways to remove it, 1 log out or 2 set the ticks to 0.

Steps to reproduce.. too tired 

Also manashield does not work, if hit by a physical attack it removes it right from the health, I have not tried other damage types.

This is on a clean build and no source edits, I downloaded the sources 2 days ago,

**Comment by DanielChabrowski** [comment] 2017-05-16 11:07
I tried different conditions, condition ids, subids and removeCondition seems to be working just fine.
[test.lua](https://gist.github.com/DanielChabrowski/f12e89112f7ec1d02e481052c0e8e5b3)

Manashield indeed does not work if subid is different than 0. It is also the case for every hasCondition check that provide no subid - therefore using the default 0. I wouldn't call it a bug since having two or more manashield, drunk, haste, paralyze, infight, outfit conditions by using subid just doesn't make much sense in the first place.

**Comment by Codinablack** [comment] 2017-08-23 22:50
I have thoroughly checked into conditions and they seem to expire and remove as expected and as intended.

**Closed** 2017-12-26 20:26 UTC
Labels: unconfirmed
