### ISSUE TITLE
Status protocol does not close connection after checking status!

### ISSUE THREAD

**Issue by gesior** [otland/forgottenserver#1470] opened 2015-07-25 09:54 UTC
Every normal server after status data sends FIN,ACK packet (I check status with "0xFF + info" packet) .
Newest TFS keeps connection open forever.
This freez acc. maker that read from socket until max. execution time (PHP).

Only change I found is this:
https://github.com/otland/forgottenserver/commit/06c179406c6fdf595f10b325af042e55c5114bae#diff-575ee7a35edffe65602c2ce54df0c677L94

And many commits about Output changes [ getConnection->close() -> disconnect() ].

Is it planned and I should rewrite acc. maker to read until it find </ xml> or you are going to fix it?

**Comment by eklundchristopher** [comment] 2015-07-25 09:57
I'd like to confirm that I've noticed this as well.

**Comment by marksamman** [comment] 2015-07-25 12:52
This seems to be because there's a pending write, preventing the connection from being closed by the close() call. This is definitely a bug and not intentional, and must be fixed before 1.2 is released, so you should not design your application expecting this behavior.

**Comment by marksamman** [comment] 2015-07-25 13:01
@djarek any ideas why the connection destructor is not called after the message has been sent?

**Comment by djarek** [comment] 2015-07-25 13:16
This would indicate that a shared_ptr to the Connection object associated with the ProtocolStatus instance is held somewhere preventing its destruction.

**Comment by ranisalt** [comment] 2015-07-25 22:08
@gesior can you bisect with a previous commit that worked properly to see in which commit exactly this problem started happening?

**Comment by gesior** [comment] 2015-07-26 08:00
I got no idea. From 1-2 weeks I got some report about Gesior2012 that freez/return white page with TFS 1.0. Yesterday someone reported me that he removed status from Gesior and page works again.
I did analyze it with newest TFS and WireShark.

**Comment by djarek** [comment] 2015-07-28 22:03
I've found the cause. The Connection object is being kept alive by the asynchronous read callback in Connection::parseHeader() or Connection::parsePacket().

**Comment by marksamman** [comment] 2015-07-28 22:04
Me too, been looking into it for the past 5 minutes, trying to see if weak_ptr to parseHeader solves it.

**Comment by marksamman** [comment] 2015-07-28 22:31
That does solve the problem, but introduces a different one. We're passing the message buffer to async_read too, which belongs to the connection, so if the connection is deleted that may be problematic.

Here's my patch FWIW:
```cpp
diff --git a/src/connection.cpp b/src/connection.cpp
index 0b90b8a..614047f 100644
--- a/src/connection.cpp
+++ b/src/connection.cpp
@@ -126,9 +126,8 @@ void Connection::accept()
 		readTimer.async_wait(std::bind(&Connection::handleTimeout, std::weak_ptr<Connection>(shared_from_this()), std::placeholders::_1));
 
 		// Read size of the first packet
-		boost::asio::async_read(*socket,
-		                        boost::asio::buffer(msg.getBuffer(), NetworkMessage::HEADER_LENGTH),
-		                        std::bind(&Connection::parseHeader, shared_from_this(), std::placeholders::_1));
+		boost::asio::async_read(*socket, boost::asio::buffer(msg.getBuffer(), NetworkMessage::HEADER_LENGTH),
+			std::bind(&Connection::parseHeaderWeak, std::weak_ptr<Connection>(shared_from_this()), std::placeholders::_1));
 	} catch (boost::system::system_error& e) {
 		if (logError) {
 			std::cout << "[Network error - Connection::accept] " << e.what() << std::endl;
@@ -139,6 +138,13 @@ void Connection::accept()
 	}
 }
 
+void Connection::parseHeaderWeak(ConnectionWeak_ptr connectionWeak, const boost::system::error_code& error)
+{
+	if (auto connection = connectionWeak.lock()) {
+		connection->parseHeader(error);
+	}
+}
+
 void Connection::parseHeader(const boost::system::error_code& error)
 {
 	std::lock_guard<std::recursive_mutex> lockClass(connectionLock);
@@ -167,13 +173,12 @@ void Connection::parseHeader(const boost::system::error_code& error)
 
 	try {
 		readTimer.expires_from_now(boost::posix_time::seconds(Connection::read_timeout));
-		readTimer.async_wait(std::bind(&Connection::handleTimeout, std::weak_ptr<Connection>(shared_from_this()),
-		                                    std::placeholders::_1));
+		readTimer.async_wait(std::bind(&Connection::handleTimeout, std::weak_ptr<Connection>(shared_from_this()), std::placeholders::_1));
 
 		// Read packet content
 		msg.setLength(size + NetworkMessage::HEADER_LENGTH);
 		boost::asio::async_read(*socket, boost::asio::buffer(msg.getBodyBuffer(), size),
-		                        std::bind(&Connection::parsePacket, shared_from_this(), std::placeholders::_1));
+			std::bind(&Connection::parsePacketWeak, std::weak_ptr<Connection>(shared_from_this()), std::placeholders::_1));
 	} catch (boost::system::system_error& e) {
 		if (logError) {
 			std::cout << "[Network error - Connection::parseHeader] " << e.what() << std::endl;
@@ -184,6 +189,13 @@ void Connection::parseHeader(const boost::system::error_code& error)
 	}
 }
 
+void Connection::parsePacketWeak(ConnectionWeak_ptr connectionWeak, const boost::system::error_code& error)
+{
+	if (auto connection = connectionWeak.lock()) {
+		connection->parsePacket(error);
+	}
+}
+
 void Connection::parsePacket(const boost::system::error_code& error)
 {
 	std::lock_guard<std::recursive_mutex> lockClass(connectionLock);
@@ -234,13 +246,11 @@ void Connection::parsePacket(const boost::system::error_code& error)
 
 	try {
 		readTimer.expires_from_now(boost::posix_time::seconds(Connection::read_timeout));
-		readTimer.async_wait(std::bind(&Connection::handleTimeout, std::weak_ptr<Connection>(shared_from_this()),
-		                                    std::placeholders::_1));
+		readTimer.async_wait(std::bind(&Connection::handleTimeout, std::weak_ptr<Connection>(shared_from_this()), std::placeholders::_1));
 
 		// Wait to the next packet
-		boost::asio::async_read(*socket,
-		                        boost::asio::buffer(msg.getBuffer(), NetworkMessage::HEADER_LENGTH),
-		                        std::bind(&Connection::parseHeader, shared_from_this(), std::placeholders::_1));
+		boost::asio::async_read(*socket, boost::asio::buffer(msg.getBuffer(), NetworkMessage::HEADER_LENGTH),
+								std::bind(&Connection::parseHeaderWeak, std::weak_ptr<Connection>(shared_from_this()), std::placeholders::_1));
 	} catch (boost::system::system_error& e) {
 		if (logError) {
 			std::cout << "[Network error - Connection::parsePacket] " << e.what() << std::endl;
diff --git a/src/connection.h b/src/connection.h
index 8cd6789..88601e5 100644
--- a/src/connection.h
+++ b/src/connection.h
@@ -100,7 +100,9 @@ class Connection : public std::enable_shared_from_this<Connection>
 		uint32_t getIP();
 
 	private:
+		static void parseHeaderWeak(ConnectionWeak_ptr connection, const boost::system::error_code& error);
 		void parseHeader(const boost::system::error_code& error);
+		static void parsePacketWeak(ConnectionWeak_ptr connection, const boost::system::error_code& error);
 		void parsePacket(const boost::system::error_code& error);
 
 		void onWriteOperation(const boost::system::error_code& error);
```


If you manage to solve it in a good way, please open a pull request.

**Comment by djarek** [comment] 2015-07-31 18:24
@marksamman 
I've come up with two solutions:
1. We split the buffer and the connection objects. This would require some redesigning and probably using a Message Pool. An advantage of this solution is that we could safely move decryption and parsing of the message to a separate thread.
2. The simpler approach would be to just close the socket in onWriteOperation() when we run out of messages and a connection close has been requested.
What do you think?

**Comment by marksamman** [comment] 2015-08-01 19:00
We'll go with option 2 to fix this bug.

**Closed** 2015-08-01 20:48 UTC
Labels: bug
