### ISSUE TITLE
monsterType:getCreatureEvents() does not list registered events.

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1437] opened 2015-07-02 16:55 UTC
I am using TFS 1.0

When I do this:
target:registerEvent(eventName)

monsterType = target:getType()
allMonsterEvents = monsterType:getCreatureEvents()

allMonsterEvents only has the creaturescripts I have added on the monster.xml
It doesn't show registered events trough LUA.

Supposed to be like that? Is it different in higher TFS versions?
##

**Comment by whitevo** [comment] 2015-07-02 17:01
I currently making dispel spell for game, and it should remove creaturescripts too.
I want to count how many creaturescripts it is removing or does monster have creaturescrips activated.

Problem is that: that function does not show registered events.. unregisterEvent() always returns true does not matter did monster have that creaturescript activated or not.

**Comment by whitevo** [comment] 2015-07-10 21:41
what do you mean by unconfirmed xD?

**Comment by Alscara** [comment] 2015-07-10 22:01
you would have to understand what the class means. monsterType pulls info about a monster from the xml. It can pull things like name, resistances, etc. monsterType cannot access actual monsters in-game. It only pulls what can be found in the xml file. This is not a bug, it's exactly as the system was designed. monsterType:getCreatureEvents() will return a creatureEvent if there is only one, or a table containing all creatureEvents within that monster's file.

**Comment by Alscara** [comment] 2015-07-10 22:03
In addition, the "unconfirmed" label means Mark has seen your issue but has not actually looked into it, or has not looked into it enough to offer a verdict on whether it's a problem or not.

**Comment by whitevo** [comment] 2015-07-11 15:29
Ah ok I understand.
Seems I have generate new table what keeps track of monster creaturescripts then xD

Although currently I just register the same event on monster each time something happens.
Doesn't seem its doing anything bad, but i can be wrong.

**Comment by ninjalulz** [comment] 2017-01-18 11:34
@ranisalt Please close this issue.

**Closed** 2017-01-18 14:20 UTC
Labels: unconfirmed
