### ISSUE TITLE
CMake issues in Visual Studio

### ISSUE THREAD

**Issue by Zbizu** [otland/forgottenserver#4616] opened 2023-12-31 16:26 UTC
Hey,
I have been trying to set up CMake compilation for Visual Studio in order to avoid all the hassle with Ubuntu VM.
Unfortunately, there is something missing as opening the folder of recently cloned repo in Visual Studio results in CMake being unable reach Crypto++ library from vcpkg directory.

I'm getting an error `-- Could NOT find cryptopp (missing: cryptopp_DIR)` directing to this line:
https://github.com/otland/forgottenserver/blob/fee42e4fb14737d7301ccd49a9ee4edaf18c0adc/CMakeLists.txt#L35

also tried with new vcpkg install, same issue

as there is code involving vcpkg in cmake configuration, I assume that at some point this way of compiling used to work

**Comment by Zbizu** [comment] 2024-01-03 13:32
more information:
I tried to checkout to old commits, but those have old fmt syntax. Seems like something around switch to c++20 broke it for Windows.

**Comment by Codinablack** [comment] 2024-03-26 05:33
We can close this as the issue isn't with TFS, or CMake (its actually all CMake's fault), its due to Cryptopp removing support for CMake as, and I quote here: "18 percent of reported bugs were from cmake". You can find this change on their github with this commit

https://github.com/weidai11/cryptopp/commit/913a9e60d375e4581d4eca7078f0786327afa258

The community now has to work on support for cmake, they do so here : https://github.com/abdes/cryptopp-cmake

**Comment by EvilHero90** [comment] 2024-05-14 15:42
This should be resolved since we switched over to `OpenSSL` #4655

**Closed by EvilHero90** 2024-05-14 15:42 UTC
