### ISSUE TITLE
removeSkillLevel

### ISSUE THREAD

**Issue by whitevo** [otland/forgottenserver#1303] opened 2015-04-20 14:50 UTC
Currently we have:
registerMethod("Player", "getSkillLevel", LuaScriptInterface::luaPlayerGetSkillLevel);

But some would like also to see is:
registerMethod("Player", "removeSkillLevel", LuaScriptInterface::luaPlayerRemoveSkillLevel);

What it should do is:
takes away 1 skillLevel and puts skilltries back to 0.

Let us calculate whatever we wanted to remove/add skilltries in LUA
Currently i have to make conditions to add skills and remove them.
Because basic methods are not good enough.

**Comment by marksamman** [comment] 2015-04-20 21:07
Duplicate of #377.

**Closed by marksamman** 2015-04-20 21:07 UTC
Labels: duplicate
