### ISSUE TITLE
[Suggestion] Move monster drop loot to Lua

### ISSUE THREAD

**Issue by gugahoa** [otland/forgottenserver#1797] opened 2016-05-18 20:30 UTC
Would it be interesting and useful to move monster drop to Lua?
I made this feature a while ago for the servers I work on, it was quite useful to make random global drops.

The approach I did was use a feature sent as PR for TFS a while ago, Monster:onSpawn, to register the onDeath event on every monster. The rest was merely passing the C++ functions that generate loot to Lua.

**Comment by wgrriffel** [comment] 2016-05-18 21:52
Signed, drops could be really fun customisable

**Comment by vankk** [comment] 2016-05-18 22:07
Signed.

**Comment by marksamman** [comment] 2016-05-19 10:46
Duplicate of #1249

**Closed by marksamman** 2016-05-19 10:46 UTC
Labels: duplicate

**Comment by gugahoa** [comment] 2016-05-19 11:27
Didn't even remember I made this same suggestion before. wow
Should have search for it before creating this issue, I'm sorry
