### ISSUE TITLE
teleport on walkback items

### ISSUE THREAD

**Issue by emil92b** [otland/forgottenserver#3458] opened 2021-05-13 23:57 UTC
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [x] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. /pos x,y,z on one of these items with uniqueid

```
<!-- Walkback when walking on quest chest -->
<movevent event="StepIn" itemid="1738" script="walkback.lua" />
<movevent event="StepIn" itemid="1740" script="walkback.lua" />
<movevent event="StepIn" fromid="1746" toid="1749" script="walkback.lua" />
```

`item.uid > 0 and item.uid <= 65535`

### Expected behaviour
i would assume it should teleport you to a free position near the item

### Actual behaviour
teleports you to a free position from your own position?

**Comment by Znote** [comment] 2021-05-14 02:39
https://github.com/otland/forgottenserver/blob/0d672412d0a6406dd3e556d1249c3eca49b12749/data/movements/scripts/walkback.lua#L1-L6

Try this:

```lua
 function onStepIn(creature, item, position, fromPosition) 
	if creature:isPlayer() and player:getGroup():getAccess() then
		return true
	end
	if item.uid > 0 and item.uid <= 65535 then 
		creature:teleportTo(fromPosition, false) 
	end 
	return true 
end 
```

**Comment by MillhioreBT** [comment] 2021-05-20 18:55
> https://github.com/otland/forgottenserver/blob/0d672412d0a6406dd3e556d1249c3eca49b12749/data/movements/scripts/walkback.lua#L1-L6
> 
> Try this:
> 
> ```lua
>  function onStepIn(creature, item, position, fromPosition) 
> 	if creature:isPlayer() and creature:getGroup():getAccess() then
> 		return true
> 	end
> 	if item.uid > 0 and item.uid <= 65535 then 
> 		creature:teleportTo(fromPosition, false) 
> 	end 
> 	return true 
> end 
> ```
> 
> What walkback does, is to send you back to the position you came from, in case of GM command `/pos` that might very well be on the other side of the world. x)
> 
> But I'm not sure what the optimal solution would be, `/pos` does what its meant to do, its just being proceeded by the walkback script when you teleport a location that triggers walkback, which is also doing just what its meant to do. Sending players back to the position they came from.

I agree with you @Znote
If I had to go to a position where there is a teleport item, then I would simply change the coordinate of the command in 1sqm only and the problem is solved

**Comment by Codinablack** [comment] 2021-06-07 22:42
Can we close this?

**Closed** 2021-06-09 10:14 UTC
Labels: question, wontfix
