### ISSUE TITLE
player:say("text" is crashing client

### ISSUE THREAD

**Issue by Olrios** [otland/forgottenserver#2714] opened 2019-11-11 21:53 UTC
If you make lua script with say("text") without adding type of text like say("text", type_of_text) it will crash client upon executing. Also server displays no informations in server's console. So this bug makes fixing lua code much harder.

### Steps to reproduce (include any configuration/script required to reproduce)

1. put this in your lua script:
creature:say("text")
2. enjoy client crash

### Expected behaviour
If there is no type_of_text definied, it should choose 1 as a default.
Or, atleast display useful informations in console with bad lua script and line of lua's code.

**Comment by Riverlance** [comment] 2019-11-13 20:19
According to the header `creature:say(text, type[, ghost = false[, target = nullptr[, position]]])`, there is no default value to `type` param. It means you should use like `creature:say("Text.", TALKTYPE_SAY)` instead.

Did you tried `creature:say("Text.", TALKTYPE_SAY)`?

**Comment by delusionx** [comment] 2019-11-16 19:08
It's not a bug, you're intentionally not using it the way it's intended to. If you need to have a default parameter, just rewrite it. There shouldn't even be any need to display information about that to the server's console because it's not related to the server, it's the client's problem if you're not passing in a text type.

**Comment by EPuncker** [comment] 2019-11-22 21:34
I think this issue can be closed since https://github.com/otland/forgottenserver/commit/1af9c7dae4937f2c27c6117cc4a6e4e870a993d8 ?

**Comment by Znote** [comment] 2019-11-23 14:01
yes, fixed in #2720

**Closed by Znote** 2019-11-23 14:01 UTC
