### ISSUE TITLE
Max items per stack

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1846] opened 2016-06-28 11:23 UTC
### Too much items on stack
1. Create 2000 pages of items on a stack ground
2. Up and down the stair
3. Crash.
### Expected behaviour

Not crash or maybe set a limit for sqm?
### Actual behaviour

The step three.
### Environment

I don't have any kinda of logs, because I already fixed this problem a few months ago. The system is Ubuntu 14.04.
### Fix

Seted the max value per ground in 500.

**Comment by darkjav** [comment] 2016-06-28 19:16
@vankk Hello, where you put the max value per ground? Thanks.

**Comment by Kamenuvol** [comment] 2016-06-28 23:45
I think you changed expected with actual behaviour not only in this issue.
About the issue, I think we should limit it to 256, in order to save bytes of "counter" too

**Comment by ranisalt** [comment] 2016-06-29 06:26
Half- and quarter-word value types might be less performant while not saving worthy amounts of memory.

**Comment by vankk** [comment] 2016-06-29 20:30
@darkjav 
The value 0xFFFF on[ tile.cpp L624](https://github.com/otland/forgottenserver/blob/master/src/tile.cpp#L624) is equal to 65535 items, I did some changes to edit this value on config.lua and I seted it to 500 items.

**Comment by wgrriffel** [comment] 2016-07-03 18:19
i've tried many ways to reproduce this, nothing happens even with 65535 items on tile up/down stair tile.

**Comment by Codex-NG** [comment] 2016-07-09 14:01
Yes @vankk 
Here is a decimal to hex converter
http://www.binaryhexconverter.com/decimal-to-hex-converter
If your not up for the math you can always just paste in google "0x1F4 to decimal" and you will get the calculator with the answer 500

**Comment by andersonfaaria** [comment] 2016-07-09 16:58
I've tried to reproduce this also but it didn't crash, either way I did the change too.

**Comment by degolaot** [comment] 2016-07-17 15:00
@andersonfaaria  You tried to buy several labels ignoring the capacity? I change the line L624 @vankk vankk said and still has to create 1,500+ pages on sqm. maybe we should change the other places too? for example:

IN > void Tile::internalAddThing(uint32_t, Thing* thing)

TileItemVector* items = makeItemList();
		if (items->size() >= 0xFFFF) {
			return /*RETURNVALUE_NOTPOSSIBLE*/;
		}

IN > void Tile::addThing(int32_t, Thing* thing)

TileItemVector* items = getItemList();
		if (items && items->size() >= 0xFFFF) {
			return /*RETURNVALUE_NOTPOSSIBLE*/;
		}


change there too?

**Comment by Kamenuvol** [comment] 2016-08-04 22:40
An idea for the limit: www.tibia.com/news/?subtopic=newsarchive&id=3667

**Comment by joseluis2g** [comment] 2016-08-05 00:20
@Kamenuvol 
```c++
if (items && items->size() >= 3E8) {
			return RETURNVALUE_NOTPOSSIBLE;
		}
```

**Comment by TwistedScorpio** [comment] 2016-08-06 02:07
OTServ SVN actually has this feature for quite a few years, why hasn't been included here yet? 
Also, need to know the exact cause for this to happen, given the client only accepts stacks in orders of 1~10.

**Comment by Codex-NG** [comment] 2016-08-07 09:04
@TwistedScorpio because not everything gets implemented into the official distro... I've been learning c++ more lately and I doubt anything I have added to the sources will be accepted as part of the official distribution not because the code I am writing is shit lol.. well maybe :p but because it isn't "tibia" related.

**Comment by Kamenuvol** [comment] 2016-09-29 03:39
I tried to reproduce, 420 pages of items created and no crash here.

**Comment by djarek** [comment] 2017-03-16 20:59
Closing issue due to old age. If the issue persists please reopen.

**Closed by djarek** 2017-03-16 20:59 UTC
Labels: unconfirmed
