### ISSUE TITLE
NPC Lib error

### ISSUE THREAD

**Issue by lipix** [otland/forgottenserver#1395] opened 2015-06-01 04:59 UTC
I got an erro, that is looping my console.
This error happens some times, but every day.

Lua Script Error: [Npc interface]
data/npc/scripts/default.lua:onThink
data/npc/lib/npcsystem/npchandler.lua:185: bad argument #1 to 'remove' (position out of bounds)
stack traceback:
        [C]: in ?
        [C]: in function 'remove'
        data/npc/lib/npcsystem/npchandler.lua:185: in function 'releaseFocus'
        data/npc/lib/npcsystem/npchandler.lua:346: in function 'unGreet'
        data/npc/lib/npcsystem/npchandler.lua:524: in function 'onThink'
        data/npc/scripts/default.lua:8: in function <data/npc/scripts/default.lua:8>
##

**Comment by ranisalt** [comment] 2015-06-01 05:34
This function is called when a player that was talking to an NPC times out or goes away. I think you have a NPC missing some configuration.

**Comment by lipix** [comment] 2015-06-01 18:12
My npc configuration is normal..

**Comment by ranisalt** [comment] 2015-06-03 14:30
Could you post on https://otland.net/forums/support.16/ with your NPC code?

**Comment by lipix** [comment] 2015-06-03 14:37
The error is on default.lua file.

**Comment by diath** [comment] 2015-06-04 08:06
I think [these lines](https://github.com/otland/forgottenserver/blob/047a130ec90af6462df9d0cff83fa2ba5f0d3b2d/data/npc/lib/npcsystem/npchandler.lua#L178-L187) should be replaced with something like:
```
shop_*[focus] = nil
```

This is because the table doesn't have sequenced entries and doesn't return a proper length, and the table.remove method prints an error when the specified index is out of bounds (as opposed to failing silently like in the previous Lua versions).

**Comment by lipix** [comment] 2015-06-04 15:28
I got error with boat NPC too.

**Comment by kanohn** [comment] 2015-07-19 18:07
The bug only occour with npcs with this param's:

Example:
<parameter key="module_travel" value="1"/>
    <parameter key="travel_destinations" value="passage,31938,31045,7,0;sea,31938,31045,7,0"/>

I Tested in ubuntu 12.04 and works fine, but in ubuntu 14.04+ get constant errors

**Comment by kanohn** [comment] 2015-07-19 21:50
i changed the lines to: shop_*[focus] = nil replacing names, and not work, how to solve this problem?

**Comment by kanohn** [comment] 2015-07-20 01:25
I saw that the error occurs when a player says "hi" to any NPC, and logout. after it, starts to make a spoof of these errors on the console.

I used ubuntu 12:04 and never gave problem with that, searching can be seen that the version of the moon at 14:04 Ubuntu or Debian 8 is more up ..

The question now is to solve this problem .. HELP!

**Comment by WibbenZ** [comment] 2017-12-26 20:13
Seeing as no one has helped to confirm this issue im closing it.
Feel free to inform us if the issue is still present.

**Closed by WibbenZ** 2017-12-26 20:13 UTC
Labels: unconfirmed
