### ISSUE TITLE
Invisibility on a tile

### ISSUE THREAD

**Issue by M4GO** [otland/forgottenserver#2211] opened 2017-03-22 15:53 UTC
TFS 1.2
i tested it with item 4545 creat 9x
http://ap.imagensbrasil.org/image/jjfEIn
and in rook use lever, i used 9x
http://ap.imagensbrasil.org/image/jjfpc5

**on windows dont work on bridge**

**Comment by M4GO** [comment] 2017-03-23 15:55
@djarek  thank you for viewing my topic, i have posted on otland and after people say this bug is from client

**Comment by djarek** [comment] 2017-03-27 21:37
If I understand you correctly the issue is on the client side. Unless there's something to be done on our side to prevent it, we can't really do anything. I'm closing this for now, if there's something more to add, please reopen.

**Closed by djarek** 2017-03-27 21:37 UTC
Labels: unconfirmed
