### ISSUE TITLE
Action scripts crash on Windows Debug Build

### ISSUE THREAD

**Issue by xmish** [otland/forgottenserver#3901] opened 2022-01-18 21:10 UTC
### Before creating an issue, please ensure:
- [ ] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the C++ code in this repository

### Steps to reproduce (include any configuration/script required to reproduce)
1. Compile TFS as Debug on Windows 10
2. Add any action script in `data/scripts/action` directory (e.g. `onUse`) 

### Expected behaviour

Prevent crashing of TFS on Windows debug build

### Actual behaviour

For these methods
```
Action::clearItemIdRange
Action::clearUniqueIdRange
Action::clearActionIdRange
```

On TFS startup there is an Exception Thrown:
```
read access violation
_Pnext was 0xFFFFFFFFFFFFFFFF.
```

I added such checks to prevent such crashes.
But this is not a solution, it needs to be investigated to check for real cause ot the issue:
```
void clearItemIdRange() {
	if (ids.empty()) {
		return;
	}

	return ids.clear();
}
#endif
```

Exception is  only thrown on TFS startup on Windows (Debug build, Release works fine). 
Build on Debian works fine too.

### Environment

- Windows 10 [Version 10.0.19042.1466]
- Visual Studio 2022 (v143)
- SDK 10.0.22000.0

**Comment by nekiro** [comment] 2022-01-20 16:56
Is it tied?
https://github.com/otland/forgottenserver/pull/3694

**Comment by xmish** [comment] 2022-01-20 17:02
> Is it tied?
> #3694
Yea its duplicate
#3692

**Comment by EPuncker** [comment] 2022-01-27 08:44
duplicate of #3692 , I'm closing this one, lets focus on that other issue, and please test PR #3694 and let us know if it works for you

**Closed by EPuncker** 2022-01-27 08:44 UTC
