### ISSUE TITLE
[BUG] Too many items in the inbox.

### ISSUE THREAD

**Issue by luanlucian93** [otland/forgottenserver#1431] opened 2015-06-25 01:37 UTC
Look:
http://i.imgur.com/MqKWFn2.png

I use command: 
select `player_id`, count(`player_id`) from `player_inboxitems` group by `player_id` having count(`player_id`) > 500

Look:
http://i.imgur.com/2DHE9ZG.png

Help me?

**Comment by ranisalt** [comment] 2015-06-25 03:20
It's not a bug and is probably a duplicate of #1403

**Closed** 2015-06-25 03:26 UTC
