### ISSUE TITLE
Death to monster in Pvp Zone Tile

### ISSUE THREAD

**Issue by walissonsantos** [otland/forgottenserver#1491] opened 2015-08-04 22:12 UTC
If a monster kill the player in a pvp zone tile, the player dies and relogin infinitely.

Sorry my bad english.

**Comment by luanlucian93** [comment] 2015-08-05 13:00
Confirmed.

**Comment by ranisalt** [comment] 2015-08-05 16:04
Can you provide a video or gif with demonstration?

**Comment by vankk** [comment] 2016-02-25 04:35
I can confirm this bug!

@ranisalt 
![animation](https://cloud.githubusercontent.com/assets/14372849/13309918/f4e92066-db5f-11e5-8a0e-3b398cfd6abc.gif)

**Comment by ranisalt** [comment] 2016-02-25 05:55
I believe it's because you are not supposed to be killed on a PvP zone tile, but that is only checked if you are hit by a player. PvP zone tiles are not supposed to host monsters, only players and summons if applicable.

**Comment by vankk** [comment] 2016-02-25 06:15
> PvP zone tiles are not supposed to host monsters

I agree with that but there is no way to fix this? Avoid this type of error.

**Comment by ninjalulz** [comment] 2017-01-18 11:33
@ranisalt Please close this issue.

**Closed** 2017-01-18 14:20 UTC
Labels: unconfirmed
