### ISSUE TITLE
Data/XML/Groups.xml/Flags dont work

### ISSUE THREAD

**Issue by EmperorEduardo** [otland/forgottenserver#2790] opened 2020-02-14 09:05 UTC
If you make any changes this it doesn't work.
`
<flag cannotusecombat="1" />
`

**Comment by EPuncker** [comment] 2020-02-14 17:38
yes it works, I've just tested

<flag cannotusecombat="1" />
try attack:
"you may not attack this creature"

<flag cannotusecombat="0" />
try attack:
succeed

**Comment by EmperorEduardo** [comment] 2020-02-15 01:43
example: `<flag cannotattackmonster="0" />`
"you may not attack this creature"

**Comment by EPuncker** [comment] 2020-02-15 02:43
yes I tested it well, also make sure that you are using [default TFS groups.xml](https://github.com/otland/forgottenserver/blob/master/data/XML/groups.xml#L41) (that is the one that I'm using), since you seem to be using an edited one that god group id is 4, so your group_id in your database should be 4 instead of 3, next time reporting a bug, try to reproduce it with vanilla TFS,
![45fbb6b6-bddc-4e50-a712-349f305a26f4](https://user-images.githubusercontent.com/4684880/74580514-bab5ad00-4f83-11ea-9383-3737c379bae9.gif)

**Comment by EmperorEduardo** [comment] 2020-02-15 12:07
I has vanilla TFS. My bad. I tested with one.
Yes now... I needed set both options from 1 to 0
<flag cannotattackmonster="0" /> 
and
<flag cannotusecombat="0" />

**Comment by EPuncker** [comment] 2020-02-15 15:41
so, bug solved? xD

**Comment by zeeb92** [comment] 2020-02-18 06:54
**<flag cannotattackplayer="0" />** doesn't seem to work.

**Comment by EPuncker** [comment] 2020-02-18 08:50
> `<flag cannotattackplayer="0" />` doesn't seem to work.
> ![error1](https://user-images.githubusercontent.com/60988327/74711601-acd28700-5224-11ea-9580-812232490d98.png)
> No changes to _groups.xml_ and character is triple checked to be **group_id 3** with **account type 5**.

`<flag cannotusecombat="0" />` is zero or one? the cannotattackplayer and cannotattackmonster works only together with that flag, you can't change only one and expect it to work...

right:

`<flag cannotusecombat="0" />
<flag cannotattackplayer="1" />`

wrong:
`<flag cannotusecombat="1" />
<flag cannotattackplayer="1" />`

**Comment by EPuncker** [comment] 2020-02-19 04:00
@EmperorEduardo was you able to understand? if you think this is not a but, you could close this issue

**Closed** 2020-02-20 16:55 UTC
Labels: unconfirmed

**Comment by zeeb92** [comment] 2020-02-23 02:10
<flag cannotusecombat="0" /> _"Can use combat"_
<flag cannotattackplayer="0" /> _"Can attack players "_
<flag cannotattackmonster="0" /> _"Can attack monsters"_

All **3** checks out as **FALSE**.
So there is obviously something wrong when I can't attack players but I can attack monsters with these settings.

**Comment by zeeb92** [comment] 2020-02-23 03:00
```
bool Combat::isProtected(const Player* attacker, const Player* target)
{
	uint32_t protectionLevel = g_config.getNumber(ConfigManager::PROTECTION_LEVEL);
	if (target->getLevel() < protectionLevel || attacker->getLevel() < protectionLevel) {
		return true;
	}

	//if (attacker->getVocationId() == VOCATION_NONE || target->getVocationId() == VOCATION_NONE) {
		//return true;
	//}

	if (attacker->getSkull() == SKULL_BLACK && attacker->getSkullClient(target) == SKULL_NONE) {
		return true;
	}

	return false;
}
```
Switch this out with the old one in the sources please so we can bury this **5+ year** old problem once and for all.
