### ISSUE TITLE
Crash with gdb log

### ISSUE THREAD

**Issue by Healek** [otland/forgottenserver#1878] opened 2016-08-18 02:35 UTC
**Steps to reproduce**
1. Debug random, 60~90h UPTime.
2. No idea to reproduce, i have the log error generated by gdb debugger.
BT:
#0  0x0000000000000091 in ?? ()
#1  0x00000000008c2a50 in Item::getTopParent() const ()
#2  0x00000000008c2b84 in Item::getTile() const ()
#3  0x0000000000a2e615 in Thing::getPosition() const ()
#4  0x00000000009b44bf in Player::postAddNotification(Thing_, Cylinder const_, int, cylinderlink_t) ()
#5  0x0000000000a3425d in Tile::postAddNotification(Thing_, Cylinder const_, int, cylinderlink_t) ()
#6  0x0000000000951698 in Map::moveCreature(Creature&, Tile&, bool) ()
#7  0x0000000000845c3c in Game::internalMoveCreature(Creature&, Tile&, unsigned int) ()
#8  0x0000000000845baf in Game::internalMoveCreature(Creature*, Direction, unsigned int) ()
#9  0x0000000000821996 in Creature::onWalk() ()
#10 0x000000000085249c in Game::checkCreatureWalk(unsigned int) ()
#11 0x00000000007ea5c4 in void std::_Mem_fn<void (Game::*)(unsigned int)>::operator()<unsigned int&, void>(Game*, unsigned int&) const ()
#12 0x00000000007e9333 in void std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int)> (Game*, unsigned int)>::__call<void, , 0ul, 1ul>(std::tuple<>&&, std::_Index_tuple<0ul, 1ul>) ()
#13 0x00000000007e648e in void std::_Bind<std::_Mem_fn<void (Game::*)(unsigned int)> (Game*, unsigned int)>::operator()<, void>() ()
#14 0x00000000007e3f95 in std::_Function_handler<void (), std::_Bind<std::_Mem_f

BT FULL
#0  0x0000000000000091 in ?? ()

No symbol table info available.
#1  0x00000000008c2a50 in Item::getTopParent() const ()

No symbol table info available.
#2  0x00000000008c2b84 in Item::getTile() const ()

No symbol table info available.
#3  0x0000000000a2e615 in Thing::getPosition() const ()

No symbol table info available.
#4  0x00000000009b44bf in Player::postAddNotification(Thing_, Cylinder const_, int, cylinderlink_t) ()

No symbol table info available.
#5  0x0000000000a3425d in Tile::postAddNotification(Thing_, Cylinder const_, int, cylinderlink_t) ()

No symbol table info available.
#6  0x0000000000951698 in Map::moveCreature(Creature&, Tile&, bool) ()

No symbol table info available.
#7  0x0000000000845c3c in Game::internalMoveCreature(Creature&, Tile&, unsigned int) ()

No symbol table info available.
#8  0x0000000000845baf in Game::internalMoveCreature(Creature*, Direction, unsigned int) ()

No symbol table info available.
#9  0x0000000000821996 in Creature::onWalk() ()

**I NO HAVE CAST SYSTEM, IM STILL USING THE LAST REVISION.**
### Expected behaviour

Crash
### Actual behaviour

Crash

**Comment by marksamman** [comment] 2016-08-25 19:41
Marked as invalid because of the steps to reproduce, but I'll leave it open because you provided a stacktrace, perhaps someone wants to look into it and figure out how this can result in a crash.

**Comment by eltom** [comment] 2016-10-15 06:24
@marksamman how i can provide a stacktrace? have a link tutorial?

**Closed** 2017-02-21 21:46 UTC
Labels: invalid
