### ISSUE TITLE
onMoveItem needs toContainer

### ISSUE THREAD

**Issue by drakylucas** [otland/forgottenserver#1684] opened 2016-01-15 01:16 UTC
You can get "fromContainer" using item:getParent():getId()
but you can't do it toContainer.
I'm trying to limit by LUA a backpack only for a specific kind of items and can't do it right now :s 

function Player:onMoveItem(item, count, fromPosition, toPosition)

**Comment by ranisalt** [comment] 2016-01-15 01:56
`onMoveItem` could be easily modified to hold `fromContainer` and `toContainer` but that would be backwards-incompatible, as other scripts relying on that would break.

**Comment by drakylucas** [comment] 2016-01-15 13:43
It doesn't work, works when you move from container to other container, but server crashes if you don't move from X container to Y container (like moving from container to ground)

**Comment by marksamman** [comment] 2016-01-15 19:13
Duplicate of #1446

**Closed by marksamman** 2016-01-15 19:13 UTC
Labels: duplicate
