### ISSUE TITLE
Lua Monster (Revscripts)

### ISSUE THREAD

**Issue by karimadnan** [otland/forgottenserver#2764] opened 2020-01-21 16:52 UTC
https://gyazo.com/6ead0e3927aa058732d7509d206b70b8

1- Monster don't spawn with skull.
2- Monster is hostile even tho it's false in flags.
3- How can i add custom mTypes to the config? ex. i'm using a monster level system.

**Comment by EPuncker** [comment] 2020-01-21 17:33
1 and 2 I can confirm, for 3 you need to ask to the person who made the monster level system, not here.

![2020-01-21 14_32_27-Window](https://user-images.githubusercontent.com/4684880/72828168-e383a480-3c5a-11ea-807d-176329af955b.png)
![2020-01-21 14_32_15-Window](https://user-images.githubusercontent.com/4684880/72828169-e41c3b00-3c5a-11ea-827a-f6e36411476e.png)

tagging @EvilHero90 just in case 😝

**Comment by Znote** [comment] 2020-01-21 17:36
I can faintly remember that skullTicks? skullDuration? inCombatDuration? had to be declared before giving someone a skull, else they would get a skull which would immediately dissapear. Making it appear as if they never got a skull.

**Comment by karimadnan** [comment] 2020-01-21 17:44
> I can faintly remember that skullTicks? skullDuration? inCombatDuration? had to be declared before giving someone a skull, else they would get a skull which would immediately dissapear. Making it appear as if they never got a skull.

not true i used creature:setSkull(3) it works fine.

**Comment by EvilHero90** [comment] 2020-01-21 19:04
Yea skull hasn't been added, will do a pr soon and about hostile I need to look a bit deeper why it's not working as intended.

**Comment by karimadnan** [comment] 2020-01-22 02:17
@EvilHero90  can you point me where can i add custom flags for lua monster?

**Comment by EvilHero90** [comment] 2020-01-24 02:43
This is weird, the hostile code just looks fine, did you actually try to leave it out completly to have it false as default? @karimadnan

**Comment by EPuncker** [comment] 2020-01-24 05:58
> This is weird, the hostile code just looks fine, did you actually try to leave it out completly to have it false as default? @karimadnan

I just tested letting it out completely and it still attacks me

**Comment by ninjalulz** [comment] 2020-01-24 13:11
Please correct me if I'm wrong (I haven't tested this "revscripts") but the script interface is being loaded before monsters, so couldn't it simple be a case of the monster actually being overwritten by XML settings (assuming it's still registered in there)? That would partially explain why it doesn't update `isHostile` properly.

**Comment by EvilHero90** [comment] 2020-01-24 16:59
> 
> 
> Please correct me if I'm wrong (I have yet to this so called "revscripts") but the script interface is being loaded before monsters, so couldn't it simply be a case of the monster actually being overwritten by XML settings (assuming it's still registered in there)? That would partially explain why it doesn't update `isHostile` properly.

That's actually a good call, if the monster is also done in xml then yes it'll be overwritten.
@EPuncker @karimadnan not sure if you used a monster which was also basicly created through xml.
Also be aware that the monster file should be placed into the "monster/lua" folder and not into "scripts/..."

**Comment by EPuncker** [comment] 2020-01-24 17:51
> > Please correct me if I'm wrong (I have yet to this so called "revscripts") but the script interface is being loaded before monsters, so couldn't it simply be a case of the monster actually being overwritten by XML settings (assuming it's still registered in there)? That would partially explain why it doesn't update `isHostile` properly.
> 
> That's actually a good call, if the monster is also done in xml then yes it'll be overwritten.
> @EPuncker @karimadnan not sure if you used a monster which was also basicly created through xml.
> Also be aware that the monster file should be placed into the "monster/lua" folder and not into "scripts/..."

yes it is a custom monster in monster/lua and unique there

**Comment by EvilHero90** [comment] 2020-01-24 17:54
can you post the full code, so I can see it @EPuncker

**Comment by EPuncker** [comment] 2020-01-24 18:09
> can you post the full code, so I can see it @EPuncker

[Treinador.txt](https://github.com/otland/forgottenserver/files/4109918/Treinador.txt)

**Comment by EPuncker** [comment] 2020-01-29 00:13
I've just checked and xml monsters are fine, only lua is hostile nonetheless

**Comment by EPuncker** [comment] 2020-02-02 14:39
this can be closed by https://github.com/otland/forgottenserver/commit/d4893313751e9734e2dc65903c288e6fa19abb3d I guess

**Closed** 2020-02-04 18:46 UTC
