### ISSUE TITLE
Md5, sha1 should be replaced

### ISSUE THREAD

**Issue by infister** [otland/forgottenserver#2645] opened 2019-08-24 13:10 UTC
### Before creating an issue, please ensure:
- [x] This is a bug in the software that resides in this repository, and not a
      support matter (use https://otland.net/forums/support.16/ for support)
- [ ] This issue is reproducible without changes to the code in this repository

### Expected behaviour

1. We should move forward and implement modern hashing algorithms such as bcrypt or PBKDF2.

### Actual behaviour

1. Current hashing algorithms are insecure, easy to brute force.

**Comment by Sickness-chan** [comment] 2019-08-24 13:16
https://github.com/otland/forgottenserver/pull/2148

**Comment by DSpeichert** [comment] 2019-08-24 16:07
Closing as duplicate of #2148

**Closed by DSpeichert** 2019-08-24 16:07 UTC
