### ISSUE TITLE
Monsters avoiding magic tiles [$5]

### ISSUE THREAD

**Issue by ghost** [otland/forgottenserver#193] opened 2013-10-27 12:21 UTC
I guess it's about pathfinding... a monster that should be able to walk over magic tiles tried to find a way that consists of the least magic tiles to walk through. Even managed to make a monster get stuck when he was in middle between 2 fire field tiles
##

**Comment by novasdream** [comment] 2015-02-05 15:25
have any critery to monster walk in magicfields ? @Znote

**Comment by Znote** [comment] 2015-02-08 10:57
Beside solving the issue, It has to be implemented in a pull request approved by @marksamman

**Comment by EPuncker** [comment] 2015-02-14 13:02
I want to suggest the addition of a new flag for monsters to make them able to walk through fields even if they are not immune to it, or even if they are not attacked (and if the way is blocked they walk on it anyway), but there are monsters that walks over it even if it damages him, like Wyrms that walk on a fire wall taking damage anyway, I hope I was clear enough and tell me if you need anything else

**Comment by darkjav** [comment] 2016-08-26 00:15
I think that the issue is here:
https://github.com/otland/forgottenserver/blob/master/src/tile.cpp#L542

Anybody know how fix it?

**Comment by Shack4l** [comment] 2016-09-27 08:18
any suggestion?

**Comment by peonso** [comment] 2016-11-05 20:26
https://github.com/TwistedScorpio/OTHire/commit/e647da449f15adef8da67f3fbc0908e6a69a348d

**Comment by DSpeichert** [comment] 2017-12-27 14:52
Was this changed/fixed by #2207?

**Comment by WibbenZ** [comment] 2017-12-27 14:59
Fixed in #2207

**Closed by WibbenZ** 2017-12-27 14:59 UTC
Labels: bounty, bug
