### ISSUE TITLE
setMaster bug

### ISSUE THREAD

**Issue by PrinterLUA** [otland/forgottenserver#1717] opened 2016-02-14 10:22 UTC
Hello,

Well i don't know if this is the right way, but E.x if i want to make a summon not summon and do setMaster(nil). It will still follow the master and it's still target from those monster who targeted when it was summon.

Thanks

```
function onUse(player, item, fromPosition, target, toPosition, isHotkey)
	if target:getMaster() then
		target:setMaster(nil)
	else
		target:setMaster(player)
		
	end
	return true
end
```

**Comment by WibbenZ** [comment] 2016-02-15 00:34
https://github.com/otland/forgottenserver/blob/master/src/luascript.cpp#L6826-L6831
It will return nil if you don't return a creature userdata value.

I guess you could remove the creature (and if you wanna keep it, create a normal monster using Game.createMonster(...))

**Comment by PrinterLUA** [comment] 2016-02-15 16:36
I'm currently doing that, but if you ask me. It's pain in the ass, since i store values on the monsters and then have to remove the monster with their values.

**Comment by WibbenZ** [comment] 2016-02-15 17:21
Then you need to change the function I linked.
And since Mark marked it as unconfirmed I suppose it should be changed :)

**Comment by PrinterLUA** [comment] 2016-02-15 17:44
The function itself, is not the problem. Since it turns the summon to a monster. But it need to notify the surrouding about the change, as it does when you turn something into a summon:
https://github.com/otland/forgottenserver/blob/master/src/monster.cpp#L1977

@marksamman , or i'm wrong about notifyng.

**Comment by dalkon** [comment] 2016-02-16 10:28
Turning the summon into a regular monster does not cancel following the summoner, do that manually.

**Closed by dalkon** 2016-02-16 10:28 UTC
Labels: unconfirmed

**Comment by PrinterLUA** [comment] 2016-02-16 12:47
About the target? Since monster target it when it was a summon. Then make it to regular monster, still cause monster attack it.

I know i can use getSpectators and remove it from target list. But would it not be better make it through source? 

@dalkon

**Comment by TheSumm** [comment] 2016-02-16 14:58
setMaster just sets the master.
Any other logic can be implemented using
````
Creature.setTarget
Creature.setFollowCreature
```

**Comment by PrinterLUA** [comment] 2016-02-16 15:23
But have one function to setMaster and unSetMaster feels smoother.

**Comment by ranisalt** [comment] 2016-02-16 15:28
You can implement `unsetMaster` purely in Lua mapping to `setMaster(nil)`.

**Comment by PrinterLUA** [comment] 2016-02-16 15:45
I mean in the SetMaster function, if it's master nil. Then it should notfiy sourrounding about the change. Now it will just make it from summon to normal monster. But those who has it in their targetList, will still attack it.

**Comment by PrinterLUA** [comment] 2016-02-16 17:31
@marksamman @dalkon 

Still considered as closed?

**Comment by marksamman** [comment] 2016-02-16 18:13
Not sure why @dalkon closed this, I think this is worth looking into if it makes sense to change the semantics of setting master to nil, but perhaps he already looked into it and decided that it's not worth it.

**Comment by PrinterLUA** [comment] 2016-02-17 11:49
Ok, well i've took also look at it. There is a few ways to tackle this. But would like to hear from @dalkon, as you said if it's worth to do it.
