### ISSUE TITLE
addEvent and coroutines

### ISSUE THREAD

**Issue by socket2810** [otland/forgottenserver#1721] opened 2016-02-17 19:53 UTC
addEvent does not work when used inside a coroutine.

Error: 

```
Lua Script Error: [TalkAction Interface]
data/talkactions/scripts/test.lua:onSay
LuaScriptInterface::luaAddEvent(). callback parameter should be a function.
```

How to reproduce:

``` lua
local thread = coroutine.create(function()
    addEvent(print, 2000, 'Hello World!')
end)

coroutine.resume(thread)
```

**Comment by ranisalt** [comment] 2016-02-17 20:36
Could you try another function? On some languages, `print` is not a function but rather a keyword (namely Python 2 does that), I'm not sure about Lua but can be.

Something like:
```lua
local thread = coroutine.create(function()
    addEvent((function(...)
        print(...)
    end), 2000, 'Hello World!')
end)

coroutine.resume(thread)
```

Could work.

**Comment by socket2810** [comment] 2016-02-17 20:41
````print```` is a function in Lua. I've only used it as a example. Any kind of function I've tried didn't work.

**Comment by WibbenZ** [comment] 2017-12-26 20:21
Seeing as no one has helped to confirm this issue im closing it.
Feel free to inform us if the issue is still present.

And FYI if any Lua function is a problem in this case - it's most likely a bug with Lua not with TFS.

**Closed by WibbenZ** 2017-12-26 20:21 UTC
Labels: unconfirmed
