### ISSUE TITLE
Error while compiling newest nightly.

### ISSUE THREAD

**Issue by thexamx** [otland/forgottenserver#1557] opened 2015-09-05 20:14 UTC
Hello i have problem with compiling the newest source.
Here's the error.
![](https://i.gyazo.com/644445dcb55d83959c4f8ede5f16f952.png)

**Comment by djarek** [comment] 2015-09-05 20:45
What version of VS is that?

**Comment by thexamx** [comment] 2015-09-06 00:35
2013

**Comment by kornholi** [comment] 2015-09-06 00:50
the build bot is also failing with this error, does the code compile with vs2015?

**Comment by ninjalulz** [comment] 2015-09-06 08:39
It compiles with VS2015 (boost 1.59.0, and mpir 2.7.0).

**Comment by thexamx** [comment] 2015-09-06 10:45
I have 2015 so i will try ans report if its working for me ;)

**Comment by thexamx** [comment] 2015-09-06 15:07
![](https://i.gyazo.com/4de7b2868b13ba2f7335cb40b7c1372c.png)

**Comment by thexamx** [comment] 2015-09-06 15:48
@ninjalulz  can u please give me link to your boost?

**Comment by conde2** [comment] 2015-09-06 16:01
I can confirm, same problem here. VS 2013

**Comment by ninjalulz** [comment] 2015-09-06 16:54
@thexamx 
> @ninjalulz can u please give me link to your boost?
You can download Boost C++ libraries from [Sourceforge](http://sourceforge.net/projects/boost/files/boost-binaries/1.59.0/), and mpir from [wbhart/mpir](https://github.com/wbhart/mpir) (You have to build mpir yourself. The VS solution can be found in the <b>build.vc14</b> directory).

**Comment by thexamx** [comment] 2015-09-06 18:07
same error even with this boost...

**Comment by ninjalulz** [comment] 2015-09-06 18:24
> same error even with this boost...

Have you changed the path for BOOST_ROOT, and changed msvc-12 to msvc-14 on [L10-11](https://github.com/otland/forgottenserver/blob/master/vc12/settings.props#L10-L11) in settings.props?

**Comment by djarek** [comment] 2015-09-06 18:30
Could you guys check if it compiles in VS 2013 with these lines _removed_?
https://github.com/otland/forgottenserver/blob/master/src/items.h#L118-L123

**Comment by thexamx** [comment] 2015-09-06 19:22
![](https://i.gyazo.com/f3019436302e30aea733d2777d03405b.png)

**Comment by DarkShinz** [comment] 2015-09-06 20:21
Same here guys.

**Comment by thexamx** [comment] 2015-09-07 14:14
Any news?

**Comment by Schiffers** [comment] 2015-09-07 17:25
same error here, alots of errors and not compile with VS 2013

**Comment by DarkShinz** [comment] 2015-09-07 17:48
Well, I've undone the changes made by Djarek at items.cpp/h and added optinal.h and it compiled just fine.

**Comment by Schiffers** [comment] 2015-09-07 17:53
optinal.h ? where you put it?

**Comment by thexamx** [comment] 2015-09-07 17:54
src folder ;p

**Comment by DarkShinz** [comment] 2015-09-07 17:59
https://github.com/otland/forgottenserver/commit/1af89f0523b7751b24bb798518cefa53b75afcbe
https://github.com/otland/forgottenserver/commit/5edb3074343ad95199a09b708d2f13ac7c0e6e0a

Those were the changes that I've undone. But, this don't fix anything. I mean, it ins't the last build after u do it. But it's useful to track whats bugging within the sources.

**Comment by thexamx** [comment] 2015-09-07 18:14
i prefer to wait for djarek to fix that :)

**Comment by marksamman** [comment] 2015-09-07 18:15
Can you try only removing these two lines: https://github.com/otland/forgottenserver/blob/master/src/items.h#L122-L123?

**Comment by DarkShinz** [comment] 2015-09-07 18:24
Already did, it does not works. Because something at Items.cpp is making a reference to it.

**Comment by djarek** [comment] 2015-09-07 19:58
This happens in VS 2013 because it only has partial support for default generated move constructors (IDK what they mean by partial but doesn't help us anyway). I'll try to find a workaround for it, but in the meantime, upgrading to VS 2015 will help.

**Comment by thexamx** [comment] 2015-09-07 22:53
Caan someone pliz give me compiled  libraries x64 + boost to vs2015 ?

**Comment by DarkShinz** [comment] 2015-09-08 02:57
http://sourceforge.net/projects/boost/files/boost-binaries/1.59.0/boost_1_59_0-msvc-14.0-64.exe/download <- Here it is.

**Comment by thexamx** [comment] 2015-09-08 17:02
djarek after reverting it doesnt works.

**Comment by djarek** [comment] 2015-09-08 18:07
@thexamx 
Have you reverted both commits I mentioned?

**Comment by thexamx** [comment] 2015-09-08 18:52
yeah both.

**Comment by thexamx** [comment] 2015-09-08 18:58
vs 2015, clean compile. 

![](https://i.gyazo.com/31ad332489b0930e1b3d9a42349635ff.png)

wtf...

**Comment by thexamx** [comment] 2015-09-08 20:27
btw when i remove those two updates i have this error:
in VS2013
![](https://i.gyazo.com/ac467d137b5104a7398ca04f92e9cf4a.png)

**Comment by DarkShinz** [comment] 2015-09-14 21:35
Thats strange. I think you missed something at both updates I've sent.

**Comment by HyphenMaster** [comment] 2015-10-23 09:01
Same problem

**Comment by HyphenMaster** [comment] 2015-11-06 06:59
any new informations about it ?

**Comment by marksamman** [comment] 2015-11-06 12:34
No. If there was, you would have seen it in this issue. Please refrain from commenting if your comment doesn't contribute to solving the issue.

**Comment by thexamx** [comment] 2015-11-06 16:58
@marksamman 
Don't be so rude ;D

**Comment by marksamman** [comment] 2015-11-06 16:59
@thexamx thanks for your contribution to this issue, I'll just choose to close it instead.

**Closed by marksamman** 2015-11-06 16:59 UTC
Labels: unconfirmed
