### ISSUE TITLE
Ghost problem

### ISSUE THREAD

**Issue by vankk** [otland/forgottenserver#1640] opened 2015-12-14 23:41 UTC
![www gifcreator me_qcidnl](https://cloud.githubusercontent.com/assets/14372849/11797625/6e93ec7c-a2ab-11e5-9903-8a9c572f3452.gif)

It suppost to be when the gamemaster log in still keep at ghost mode.

**Comment by marksamman** [comment] 2015-12-15 11:08
No, it's working as intended, also duplicate of #99

**Closed by marksamman** 2015-12-15 11:08 UTC
Labels: duplicate, invalid
