### ISSUE TITLE
[BUG] Serious Mistake

### ISSUE THREAD

**Issue by kaiquefb** [otland/forgottenserver#1385] opened 2015-05-26 22:51 UTC
Hello friends.

I would like to share a very serious bug, which has in all OTServ 1.0+
The Bug is very simple needs a few more hours to get to do it.
I made a video to demonstrate how it works, but I will try to explain in a better way.
The bug is to buy a house, and buy several Parcel, Present. and several random items, to stay with an absurd weight. Put everything in a bag and place it in your home. It has to be very heavy to run. So soon after Use the command !leavehouse and items iram to inbox. as well u just relog the char and the entire server will crash. In the video does not have any player on only 1. Imagine a server with more than 400 online. This is tragic.

I noticed that the depot there is a weight limit. It would be interesting to put this limit also in the Inbox, because I think that would solve the case, and if the player has exceeded the weight limit when using the command !leavehouse ? Unfortunately the rest of the items will be automatically deleted. I do not know if that would be the correct way to do this is just an idea.

Well, follow the video link showing how the bug works.

http://youtu.be/bmVI9gk-msU

:(

**Comment by ranisalt** [comment] 2015-05-27 03:34
This is a known issue. We don't know what happens in the same conditions at Cipsoft Tibia. Do you have a clue?

**Comment by Zbizu** [comment] 2015-05-27 11:41
they do it during "server save" so server is offline when they move house items to inbox

**Comment by TheSumm** [comment] 2015-05-27 11:58
The problem is not moving the item to inbox, the problem seems to be saving / loading of items in depot / inbox.

**Comment by kaiquefb** [comment] 2015-05-27 12:24
But the problem is when you save the character.
so it is possible to get this nonsense peopl if items are for the inbox, if the items stay in the house, it will not use the character to save but straight home. And this will have no problem because it does not lock.

The solution would be to put weight limit in the inbox if pass that limit the rest of the items MT will be deleted. I think this would be the solution.

**Comment by Luckey1729** [comment] 2015-05-27 14:42
So this is essentially a duplicate of #1150.

**Closed** 2015-05-27 19:00 UTC
Labels: duplicate
