### ISSUE TITLE
Bug inbox + npc

### ISSUE THREAD

**Issue by degolaot** [otland/forgottenserver#1681] opened 2016-01-10 10:55 UTC
Hello,
Today a player showed me a bug that was crashing the server, it works buying several shopping bag from NPC until X oz, after throwing everything inside the house only say !Leavehouse .
The bug work too selling itens (backpacks per example) on marketing, after this only cancel (all itens canceled go to inbox).

He buy with shopping bag: http://i.imgur.com/DiIZWma.png

Only 3 pages (but many oz) and freeze: http://prntscr.com/9o9dsc

Ready, done a bug , if the character be relog the server will freeze, my server dont crash only freeze and much!

**Comment by degolaot** [comment] 2016-01-10 11:15
Any for repair this globalevents for fix this bug?

http://pastebin.com/NsYv17kj

**Comment by marksamman** [comment] 2016-01-10 17:44
Duplicate of #1150

**Closed by marksamman** 2016-01-10 17:44 UTC
Labels: duplicate
