### ISSUE TITLE
Please put a limit on the receiving Mailbox

### ISSUE THREAD

**Issue by walissonsantos** [otland/forgottenserver#1160] opened 2015-01-21 05:17 UTC
Is very vuneravel servers, there is no limit equal the depot, after a certain amount if the player relog the server is giving lag

Example:

03:20 You see a green backpack (Vol:20).
It weighs 177569.60 oz.

**Comment by marksamman** [comment] 2015-01-21 12:07
Duplicate of #1150. If you want to give an issue more attention you can back it by placing a bounty.

**Closed by marksamman** 2015-01-21 12:07 UTC
Labels: duplicate
